description: Settings for the photochemical model.

atmosphere-grid:
  bottom: 0.0 # cm
  top: 1.0e7 # cm
  number-of-layers: 200

photolysis-grid:
  regular-grid: true
  lower-wavelength: 92.5 # nm
  upper-wavelength: 855.0 # nm
  number-of-bins: 200
  # input-file: my/input/file.txt

planet:
  use-background-gas: true
  background-gas: N2
  surface-pressure: 1.013 # bar
  planet-mass: 5.972e27 # grams
  planet-radius: 6.371e8 # cm. Radius to bottom of atmosphere-grid
  surface-albedo: 0.25 # cm
  diurnal-averaging-factor: 0.5
  solar-zenith-angle: 50.0
  diff-lim-hydrogen-escape: true
  water:
    fix-water-in-troposphere: false
    gas-rainout: true
    rainfall-rate: 1
    tropopause-altitude: 1.1e6 # cm
    water-condensation: true
    condensation-rate: {A: 1.0e-5, rhc: 0.01, rh0: 0.015}

particles:
- name: H2SO4aer
  condensation-rate: {A: 1.0e-5, rhc: 1.0, rh0: 1.05}
- name: HCNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: HCCCNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: CH3CNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H2aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H4aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H6aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C4H4aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: N2Oaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: NH3aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}  
  
boundary-conditions:
- name: H2O
  lower-boundary: {type: mix, mix: 0.017451675027637493}
  upper-boundary: {type: veff, veff: 0.0}
- name: CO2
  lower-boundary: {type: mix, mix: 10e-2}
  upper-boundary: {type: veff, veff: 0.0}

# Wogan and Catling 2020 C = 5 case for outgassing at 4 Ga.
- name: CO
  lower-boundary: {type: vdep + dist flux, vdep: 1.0e-8, flux: 3.845E+10, height: 10.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2
  lower-boundary: {type: flux, flux: 1.967e11}
  upper-boundary: {type: veff, veff: 0.0}
# I will ignore these for now.
# - name: H2S
#   lower-boundary: {type: vdep + dist flux, vdep: 0.02, flux: 3.253E+10, height: 10.0}
#   upper-boundary: {type: veff, veff: 0.0}
# - name: SO2
#   lower-boundary: {type: vdep + dist flux, vdep: 1.0, flux: 1.721E+09, height: 10.0}
#   upper-boundary: {type: veff, veff: 0.0}

# unimportant.
- name: HCN
  lower-boundary: {type: vdep, vdep: 0.007}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCCCN
  lower-boundary: {type: vdep, vdep: 0.007}
  upper-boundary: {type: veff, veff: 0.0}
  
  
# we take just 2 short-lived species
- name: O1D
  type: short lived
- name: N2D
  type: short lived
  
# Boundary conditions from Arney et al (2016).
# Most of these probably do not matter that much.
- name: O
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: H
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: OH
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: HO2
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2O2
  lower-boundary: {type: vdep, vdep: 0.2}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCO
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2CO
  lower-boundary: {type: vdep, vdep: 2e-1}
  upper-boundary: {type: veff, veff: 0.0}
- name: CH3
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: "NO"
  lower-boundary: {type: vdep, vdep: 0.0003}
  upper-boundary: {type: veff, veff: 0.0}
- name: NO2
  lower-boundary: {type: vdep, vdep: 0.003}
  upper-boundary: {type: veff, veff: 0.0}
- name: O3
  lower-boundary: {type: vdep, vdep: 0.07}
  upper-boundary: {type: veff, veff: 0.0}
- name: HNO3
  lower-boundary: {type: vdep, vdep: 0.2}
  upper-boundary: {type: veff, veff: 0.0}
- name: HSO
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2SO4
  lower-boundary: {type: vdep, vdep: 1.0}
  upper-boundary: {type: veff, veff: 0.0}
  
# Also following Arney et al. (2016), I
# apply 0.01 cm/s deposition velocities to particles
# that actually form in these atmospheres
- name: H2SO4aer
  lower-boundary: {type: vdep, vdep: 0.01}
  upper-boundary: {type: veff, veff: 0.0}
- name: S8aer
  lower-boundary: {type: vdep, vdep: 0.01}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCaer1
  lower-boundary: {type: vdep, vdep: 0.01}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCaer2
  lower-boundary: {type: vdep, vdep: 0.01}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCaer3
  lower-boundary: {type: vdep, vdep: 0.01}
  upper-boundary: {type: veff, veff: 0.0}

